version: "3.7"

services:
  postgres_db:
    image: postgres:15
    hostname: postgres_db
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: prisma
    ports:
      - "5433:5432"
    networks:
      - prisma-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 2s
      retries: 20

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true # Keeps the container running for debugging
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:prisma@postgres_db:5432/postgres?schema=public"
    networks:
      - prisma-network
  prisma-studio:
    image: node:22-alpine
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npx prisma studio --port 5555 --browser none
    ports:
      - "5555:5555"
    environment:
      DATABASE_URL: "postgresql://postgres:prisma@postgres_db:5432/postgres?schema=public"
    networks:
      - prisma-network
    depends_on:
      postgres_db:
        condition: service_healthy
      server:
        condition: service_started
networks:
  prisma-network:
    name: prisma-network
